# Generated by Django 3.0.7 on 2020-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Education', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Position', models.CharField(max_length=30)),
            ],
        ),
    ]
